//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerStoreWPFEntities : DbContext
    {
        public ManagerStoreWPFEntities()
            : base("name=ManagerStoreWPFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CustomerTable> CustomerTable { get; set; }
        public virtual DbSet<InputDetailTable> InputDetailTable { get; set; }
        public virtual DbSet<InputTable> InputTable { get; set; }
        public virtual DbSet<OutPutDetailTable> OutPutDetailTable { get; set; }
        public virtual DbSet<OutputTable> OutputTable { get; set; }
        public virtual DbSet<ProductTable> ProductTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<SupplierTable> SupplierTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
    }
}
